//@version=6
indicator(title="Keltner Channels", shorttitle="KC", overlay=true, timeframe="", timeframe_gaps=true)
length = input.int(20, minval=1)
mult = input(1.0, "Multiplier")
src = input(close, title="Source")
exp = input(true, "Use Exponential MA", display = display.data_window)
BandsStyle = input.string("Average True Range", options = ["Average True Range", "True Range", "Range"], title="Bands Style", display = display.data_window)
atrlength = input(10, "ATR Length", display = display.data_window)


esma(source, length)=>
	s = ta.sma(source, length)
	e = ta.ema(source, length)
	exp ? e : s
ma = esma(src, length)

rangema = BandsStyle == "True Range" ? ta.tr(true) : BandsStyle == "Average True Range" ? ta.atr(atrlength) : ta.rma(high - low, length)


upper1 = ma + rangema * mult
upper2 = ma + rangema * mult * 2
upper3 = ma + rangema * mult * 3
upper4 = ma + rangema * mult * 4

lower1 = ma - rangema * mult
lower2 = ma - rangema * mult * 2
lower3 = ma - rangema * mult * 3
lower4 = ma - rangema * mult * 4
u1 = plot(upper1, color=#2962FF, title="Upper1")
u2 = plot(upper2, color=#29ffea, title="Upper2")
u3 = plot(upper3, color=#f4ff29, title="Upper3")
u4 = plot(upper4, color=#ff8929, title="Upper4")

plot(ma, color=#ff2929, title="ATR-Main")
l1 = plot(lower1, color=#2962FF, title="Lower1")
l2 = plot(lower2, color=#29ffea, title="Upper2")
l3 = plot(lower3, color=#f4ff29, title="Upper3")
l4 = plot(lower4, color=#ff8929, title="Upper4")
fill(u4, l4, color=color.rgb(33, 150, 243, 95), title="Background")